services:

  # Aplicação Spring Boot responsável pelos pagamentos.
  pagamento-service:
    build:
      context: .
      dockerfile: Dockerfile

    image: pagamento-service:local
    container_name: pagamento-service-app

    environment:
      DB_URL: jdbc:postgresql://pagamento-postgres:5432/pagamentodb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

      SERVER_PORT: 8081

      SPRING_KAFKA_LISTENER_AUTO_STARTUP: "true"
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092

    ports:
      - "8081:8081"

    depends_on:
      pagamento-postgres:
        condition: service_healthy

    # Participa da rede privada do pagamento e da rede compartilhada.
    networks:
      - pagamento-network
      - recomeco-network-pagamento


  # PostgreSQL exclusivo do pagamento-service.
  pagamento-postgres:
    image: postgres:17
    container_name: pagamento-postgres

    environment:
      POSTGRES_DB: pagamentodb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"

    volumes:
      - pagamento-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pagamentodb"]
      interval: 5s
      timeout: 3s
      retries: 10

    # O banco participa somente da rede privada.
    networks:
      - pagamento-network


volumes:

  # Nome físico fixo, independente do projeto Compose utilizado.
  pagamento-postgres-data:
    name: recomeco-stack-local_pagamento-postgres-data


networks:

  # Rede privada entre pagamento-service e pagamento-postgres.
  pagamento-network:

  # Este nome lógico é exclusivo dentro do arquivo.
  # O campo name aponta para a rede real compartilhada.
  recomeco-network-pagamento:
    name: recomeco-network
    external: true